"""baseline_from_live_schema

Revision ID: 001_baseline_from_live_schema
Revises:
Create Date: 2026-04-25

PHASE 9 — Baseline migration generated from the live Who-Dis schema.

GENERATION PROCEDURE (operator runs once during Plan 06 cutover, per Pitfall 5
in 09-RESEARCH.md):

  1. On the legacy host, dump the live schema:
       bash scripts/cutover/dump_live_schema.sh > /tmp/live_schema.sql

  2. On a temp Postgres (clean DB) — the SandCastle host or a local docker:
       psql -d temp_whodis -f /tmp/live_schema.sql

  3. Point Alembic at temp_whodis and autogenerate the baseline:
       DATABASE_URL=postgresql://.../temp_whodis \\
         alembic revision --autogenerate -m "baseline_from_live_schema"

     Alembic will write a NEW versions/ file. Replace the body of THIS file
     (001_baseline_from_live_schema.py) with the generated upgrade()/downgrade()
     content; keep this file's revision id and Create Date.

  4. Hand-review for known false positives (custom indexes, sequences, comments).
     Verify with a follow-up `alembic revision --autogenerate -m "verify_clean"`
     against the same temp DB — it must produce an empty diff (T-09-04-03).

  5. Commit the populated baseline.

  6. On the SandCastle host, after `pg_restore` of the full live dump into
     whodis_db, run `alembic stamp head` (NOT `alembic upgrade head` — the
     schema is already in place from pg_restore).

Until step 5 is complete, this scaffold is a no-op (upgrade/downgrade are
empty). `alembic upgrade head` against an empty whodis_db will succeed but
create NO tables; the operator MUST run pg_restore first (or populate this
file's body with autogenerated DDL for a fresh install without live data).

After step 5, this file becomes the canonical schema definition for all future
Alembic migrations. Subsequent migrations (002_*, 003_*, ...) layer on top.

SECURITY NOTE (T-09-04-01): dump files (/tmp/live_schema.sql, /tmp/live_data.sql)
live on the operator host. Run `chmod 600 /tmp/live_*.sql` and delete them after
cutover is confirmed. Never commit these files.
"""

# revision identifiers, used by Alembic.
revision = "001_baseline_from_live_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # SCAFFOLD — replace with autogenerated DDL during Plan 06 cutover.
    # See module docstring for the generation procedure.
    pass


def downgrade() -> None:
    # SCAFFOLD — replace with autogenerated drop DDL during Plan 06 cutover.
    pass
