"""baseline_from_live_schema

Revision ID: 001_baseline_from_live_schema
Revises:
Create Date: 2026-04-25

PHASE 9 — Baseline migration capturing the live Who-Dis schema as the canonical
Alembic starting point. All subsequent migrations (002_*, 003_*, ...) layer on
top of this file.

GENERATION (2026-04-26): The body of upgrade()/downgrade() below was produced by
running `alembic revision --autogenerate` against an empty Postgres database
with the current `app.models.*` SQLAlchemy classes loaded as target_metadata,
then transplanted into this file (revision id and down_revision preserved).
This matches the live schema produced by `db.create_all()` during the original
SandCastle deploy.

OPERATOR RUNBOOK
----------------

Fresh install (no live data — green-field):
  alembic upgrade head     # runs upgrade() below; creates the 20 tables

Migrating an existing live database (data already present):
  pg_restore (or pg_dump | psql) the live data into the target Postgres FIRST,
  then `alembic stamp head` to mark the schema at this revision WITHOUT
  re-running CREATE TABLE.

VERIFICATION (T-09-04-03):
  After applying this baseline to an empty DB, a follow-up
  `alembic revision --autogenerate -m "verify_clean"` MUST produce an empty
  diff against the same models. If it does not, the model definitions have
  drifted from the schema captured here and a new migration is required.

SECURITY NOTE (T-09-04-01):
  Schema dumps used during development MUST NOT be committed. Keep them
  outside the repo and chmod 600 on the operator host.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "001_baseline_from_live_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.create_table(
        "access_attempts",
        sa.Column("requested_path", sa.String(length=500), nullable=True),
        sa.Column("auth_method", sa.String(length=50), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_email", sa.String(length=255), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column(
            "additional_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_access_attempts_created_at"),
        "access_attempts",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_access_attempts_ip_address"),
        "access_attempts",
        ["ip_address"],
        unique=False,
    )
    op.create_index(
        op.f("ix_access_attempts_session_id"),
        "access_attempts",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_access_attempts_success"), "access_attempts", ["success"], unique=False
    )
    op.create_index(
        op.f("ix_access_attempts_user_email"),
        "access_attempts",
        ["user_email"],
        unique=False,
    )

    op.create_table(
        "api_tokens",
        sa.Column("service_name", sa.String(length=50), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("token_type", sa.String(length=20), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("last_refreshed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "additional_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_api_tokens_created_at"), "api_tokens", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_api_tokens_expires_at"), "api_tokens", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_api_tokens_service_name"), "api_tokens", ["service_name"], unique=True
    )

    op.create_table(
        "audit_log",
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("user_role", sa.String(length=50), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target_resource", sa.String(length=500), nullable=True),
        sa.Column("search_query", sa.String(length=500), nullable=True),
        sa.Column("search_results_count", sa.Integer(), nullable=True),
        sa.Column("search_services", sa.Text(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_email", sa.String(length=255), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column(
            "additional_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_log_created_at"), "audit_log", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_event_type"), "audit_log", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_ip_address"), "audit_log", ["ip_address"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_search_query"), "audit_log", ["search_query"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_session_id"), "audit_log", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_success"), "audit_log", ["success"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_user_email"), "audit_log", ["user_email"], unique=False
    )

    op.create_table(
        "compliance_check_runs",
        sa.Column("run_id", sa.String(length=100), nullable=False),
        sa.Column("run_type", sa.String(length=50), nullable=False),
        sa.Column("scope", sa.String(length=100), nullable=True),
        sa.Column("scope_filter", sa.String(length=255), nullable=True),
        sa.Column("total_employees", sa.Integer(), nullable=True),
        sa.Column("total_checks", sa.Integer(), nullable=True),
        sa.Column("compliant_count", sa.Integer(), nullable=True),
        sa.Column("violation_count", sa.Integer(), nullable=True),
        sa.Column("error_count", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("started_by", sa.String(length=255), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "additional_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_compliance_check_runs_created_at"),
        "compliance_check_runs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_check_runs_run_id"),
        "compliance_check_runs",
        ["run_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_compliance_check_runs_started_at"),
        "compliance_check_runs",
        ["started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_check_runs_started_by"),
        "compliance_check_runs",
        ["started_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_check_runs_status"),
        "compliance_check_runs",
        ["status"],
        unique=False,
    )

    op.create_table(
        "employee_profiles",
        sa.Column("upn", sa.String(length=255), nullable=False),
        sa.Column("ks_user_serial", sa.Integer(), nullable=True),
        sa.Column("ks_last_login_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ks_login_lock", sa.String(length=1), nullable=True),
        sa.Column("live_role", sa.String(length=255), nullable=True),
        sa.Column("test_role", sa.String(length=255), nullable=True),
        sa.Column("keystone_expected_role", sa.String(length=255), nullable=True),
        sa.Column("ukg_job_code", sa.String(length=50), nullable=True),
        sa.Column("photo_data", sa.LargeBinary(), nullable=True),
        sa.Column("photo_content_type", sa.String(length=50), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("upn"),
    )
    op.create_index(
        "idx_employee_profiles_keystone_expected_role",
        "employee_profiles",
        ["keystone_expected_role"],
        unique=False,
    )
    op.create_index(
        "idx_employee_profiles_ks_login_lock",
        "employee_profiles",
        ["ks_login_lock"],
        unique=False,
    )
    op.create_index(
        "idx_employee_profiles_live_role",
        "employee_profiles",
        ["live_role"],
        unique=False,
    )
    op.create_index(
        "idx_employee_profiles_upn", "employee_profiles", ["upn"], unique=False
    )

    op.create_table(
        "employee_role_assignments",
        sa.Column("employee_upn", sa.String(length=255), nullable=False),
        sa.Column("system_name", sa.String(length=100), nullable=False),
        sa.Column("role_name", sa.String(length=255), nullable=False),
        sa.Column("assignment_type", sa.String(length=50), nullable=True),
        sa.Column("assignment_source", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("assigned_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_verified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "additional_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "employee_upn",
            "system_name",
            "role_name",
            name="uq_employee_role_assignment",
        ),
    )
    op.create_index(
        op.f("ix_employee_role_assignments_created_at"),
        "employee_role_assignments",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employee_role_assignments_employee_upn"),
        "employee_role_assignments",
        ["employee_upn"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employee_role_assignments_is_active"),
        "employee_role_assignments",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employee_role_assignments_last_verified"),
        "employee_role_assignments",
        ["last_verified"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employee_role_assignments_role_name"),
        "employee_role_assignments",
        ["role_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employee_role_assignments_system_name"),
        "employee_role_assignments",
        ["system_name"],
        unique=False,
    )

    op.create_table(
        "error_log",
        sa.Column("error_type", sa.String(length=100), nullable=False),
        sa.Column("stack_trace", sa.Text(), nullable=True),
        sa.Column("request_path", sa.String(length=500), nullable=True),
        sa.Column("request_method", sa.String(length=10), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_email", sa.String(length=255), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column(
            "additional_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_error_log_created_at"), "error_log", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_error_log_error_type"), "error_log", ["error_type"], unique=False
    )
    op.create_index(
        op.f("ix_error_log_ip_address"), "error_log", ["ip_address"], unique=False
    )
    op.create_index(
        op.f("ix_error_log_session_id"), "error_log", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_error_log_severity"), "error_log", ["severity"], unique=False
    )
    op.create_index(
        op.f("ix_error_log_success"), "error_log", ["success"], unique=False
    )
    op.create_index(
        op.f("ix_error_log_user_email"), "error_log", ["user_email"], unique=False
    )

    op.create_table(
        "genesys_groups",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("member_count", sa.Integer(), nullable=True),
        sa.Column("date_modified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("service_id", sa.String(length=255), nullable=False),
        sa.Column("service_name", sa.String(length=100), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "additional_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_genesys_groups_created_at"),
        "genesys_groups",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_genesys_groups_is_active"),
        "genesys_groups",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_genesys_groups_service_id"),
        "genesys_groups",
        ["service_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_genesys_groups_service_name"),
        "genesys_groups",
        ["service_name"],
        unique=False,
    )

    op.create_table(
        "genesys_locations",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("emergency_number", sa.String(length=50), nullable=True),
        sa.Column("address", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("service_id", sa.String(length=255), nullable=False),
        sa.Column("service_name", sa.String(length=100), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "additional_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_genesys_locations_created_at"),
        "genesys_locations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_genesys_locations_is_active"),
        "genesys_locations",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_genesys_locations_service_id"),
        "genesys_locations",
        ["service_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_genesys_locations_service_name"),
        "genesys_locations",
        ["service_name"],
        unique=False,
    )

    op.create_table(
        "genesys_skills",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("service_id", sa.String(length=255), nullable=False),
        sa.Column("service_name", sa.String(length=100), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "additional_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_genesys_skills_created_at"),
        "genesys_skills",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_genesys_skills_is_active"),
        "genesys_skills",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_genesys_skills_service_id"),
        "genesys_skills",
        ["service_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_genesys_skills_service_name"),
        "genesys_skills",
        ["service_name"],
        unique=False,
    )

    op.create_table(
        "job_codes",
        sa.Column("job_code", sa.String(length=50), nullable=False),
        sa.Column("job_title", sa.String(length=255), nullable=False),
        sa.Column("department", sa.String(length=255), nullable=True),
        sa.Column("job_family", sa.String(length=100), nullable=True),
        sa.Column("job_level", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "additional_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_codes_created_at"), "job_codes", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_job_codes_department"), "job_codes", ["department"], unique=False
    )
    op.create_index(
        op.f("ix_job_codes_is_active"), "job_codes", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_job_codes_job_code"), "job_codes", ["job_code"], unique=True
    )

    op.create_table(
        "search_cache",
        sa.Column("search_query", sa.String(length=500), nullable=False),
        sa.Column("search_type", sa.String(length=50), nullable=False),
        sa.Column(
            "result_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "additional_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_search_cache_created_at"), "search_cache", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_search_cache_expires_at"), "search_cache", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_search_cache_search_query"),
        "search_cache",
        ["search_query"],
        unique=False,
    )
    op.create_index(
        op.f("ix_search_cache_search_type"),
        "search_cache",
        ["search_type"],
        unique=False,
    )

    op.create_table(
        "system_roles",
        sa.Column("role_name", sa.String(length=255), nullable=False),
        sa.Column("system_name", sa.String(length=100), nullable=False),
        sa.Column("role_type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "additional_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "role_name", "system_name", "role_type", name="uq_system_role"
        ),
    )
    op.create_index(
        op.f("ix_system_roles_created_at"), "system_roles", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_system_roles_is_active"), "system_roles", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_system_roles_role_name"), "system_roles", ["role_name"], unique=False
    )
    op.create_index(
        op.f("ix_system_roles_role_type"), "system_roles", ["role_type"], unique=False
    )
    op.create_index(
        op.f("ix_system_roles_system_name"),
        "system_roles",
        ["system_name"],
        unique=False,
    )

    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_index(op.f("ix_users_last_login"), "users", ["last_login"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)

    op.create_table(
        "compliance_checks",
        sa.Column("check_run_id", sa.String(length=100), nullable=False),
        sa.Column("employee_upn", sa.String(length=255), nullable=False),
        sa.Column("job_code", sa.String(length=50), nullable=False),
        sa.Column("system_name", sa.String(length=100), nullable=False),
        sa.Column("role_name", sa.String(length=255), nullable=False),
        sa.Column("expected_mapping_type", sa.String(length=50), nullable=True),
        sa.Column("actual_assignment", sa.Boolean(), nullable=False),
        sa.Column("compliance_status", sa.String(length=50), nullable=False),
        sa.Column("violation_severity", sa.String(length=20), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("remediation_action", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "additional_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(["check_run_id"], ["compliance_check_runs.run_id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_compliance_checks_check_run_id"),
        "compliance_checks",
        ["check_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_checks_compliance_status"),
        "compliance_checks",
        ["compliance_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_checks_created_at"),
        "compliance_checks",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_checks_employee_upn"),
        "compliance_checks",
        ["employee_upn"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_checks_job_code"),
        "compliance_checks",
        ["job_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_checks_system_name"),
        "compliance_checks",
        ["system_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_checks_violation_severity"),
        "compliance_checks",
        ["violation_severity"],
        unique=False,
    )

    op.create_table(
        "job_role_mappings",
        sa.Column("job_code_id", sa.Integer(), nullable=False),
        sa.Column("system_role_id", sa.Integer(), nullable=False),
        sa.Column("mapping_type", sa.String(length=50), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "additional_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(["job_code_id"], ["job_codes.id"]),
        sa.ForeignKeyConstraint(["system_role_id"], ["system_roles.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "job_code_id", "system_role_id", name="uq_job_role_mapping"
        ),
    )
    op.create_index(
        op.f("ix_job_role_mappings_created_at"),
        "job_role_mappings",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_role_mappings_created_by"),
        "job_role_mappings",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_role_mappings_job_code_id"),
        "job_role_mappings",
        ["job_code_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_role_mappings_mapping_type"),
        "job_role_mappings",
        ["mapping_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_role_mappings_system_role_id"),
        "job_role_mappings",
        ["system_role_id"],
        unique=False,
    )

    op.create_table(
        "user_notes",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("context", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_notes_context"), "user_notes", ["context"], unique=False
    )
    op.create_index(
        op.f("ix_user_notes_created_at"), "user_notes", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_notes_created_by"), "user_notes", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_user_notes_is_active"), "user_notes", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_user_notes_user_id"), "user_notes", ["user_id"], unique=False
    )

    op.create_table(
        "user_sessions",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_email", sa.String(length=255), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("last_activity", sa.DateTime(timezone=True), nullable=True),
        sa.Column("warning_shown", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_sessions_created_at"),
        "user_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_sessions_expires_at"),
        "user_sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_sessions_ip_address"),
        "user_sessions",
        ["ip_address"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_sessions_is_active"), "user_sessions", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_user_sessions_last_activity"),
        "user_sessions",
        ["last_activity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_sessions_user_email"),
        "user_sessions",
        ["user_email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False
    )

    op.create_table(
        "job_role_mapping_history",
        sa.Column("mapping_id", sa.Integer(), nullable=True),
        sa.Column("job_code", sa.String(length=50), nullable=False),
        sa.Column("role_name", sa.String(length=255), nullable=False),
        sa.Column("system_name", sa.String(length=100), nullable=False),
        sa.Column("old_mapping_type", sa.String(length=50), nullable=True),
        sa.Column("new_mapping_type", sa.String(length=50), nullable=True),
        sa.Column("old_priority", sa.Integer(), nullable=True),
        sa.Column("new_priority", sa.Integer(), nullable=True),
        sa.Column("change_type", sa.String(length=20), nullable=False),
        sa.Column("changed_by", sa.String(length=255), nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.Column(
            "additional_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["mapping_id"], ["job_role_mappings.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_role_mapping_history_change_type"),
        "job_role_mapping_history",
        ["change_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_role_mapping_history_changed_by"),
        "job_role_mapping_history",
        ["changed_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_role_mapping_history_created_at"),
        "job_role_mapping_history",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_role_mapping_history_job_code"),
        "job_role_mapping_history",
        ["job_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_role_mapping_history_mapping_id"),
        "job_role_mapping_history",
        ["mapping_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_index(
        op.f("ix_job_role_mapping_history_mapping_id"),
        table_name="job_role_mapping_history",
    )
    op.drop_index(
        op.f("ix_job_role_mapping_history_job_code"),
        table_name="job_role_mapping_history",
    )
    op.drop_index(
        op.f("ix_job_role_mapping_history_created_at"),
        table_name="job_role_mapping_history",
    )
    op.drop_index(
        op.f("ix_job_role_mapping_history_changed_by"),
        table_name="job_role_mapping_history",
    )
    op.drop_index(
        op.f("ix_job_role_mapping_history_change_type"),
        table_name="job_role_mapping_history",
    )
    op.drop_table("job_role_mapping_history")

    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_user_email"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_last_activity"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_is_active"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_ip_address"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_expires_at"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_created_at"), table_name="user_sessions")
    op.drop_table("user_sessions")

    op.drop_index(op.f("ix_user_notes_user_id"), table_name="user_notes")
    op.drop_index(op.f("ix_user_notes_is_active"), table_name="user_notes")
    op.drop_index(op.f("ix_user_notes_created_by"), table_name="user_notes")
    op.drop_index(op.f("ix_user_notes_created_at"), table_name="user_notes")
    op.drop_index(op.f("ix_user_notes_context"), table_name="user_notes")
    op.drop_table("user_notes")

    op.drop_index(
        op.f("ix_job_role_mappings_system_role_id"), table_name="job_role_mappings"
    )
    op.drop_index(
        op.f("ix_job_role_mappings_mapping_type"), table_name="job_role_mappings"
    )
    op.drop_index(
        op.f("ix_job_role_mappings_job_code_id"), table_name="job_role_mappings"
    )
    op.drop_index(
        op.f("ix_job_role_mappings_created_by"), table_name="job_role_mappings"
    )
    op.drop_index(
        op.f("ix_job_role_mappings_created_at"), table_name="job_role_mappings"
    )
    op.drop_table("job_role_mappings")

    op.drop_index(
        op.f("ix_compliance_checks_violation_severity"), table_name="compliance_checks"
    )
    op.drop_index(
        op.f("ix_compliance_checks_system_name"), table_name="compliance_checks"
    )
    op.drop_index(op.f("ix_compliance_checks_job_code"), table_name="compliance_checks")
    op.drop_index(
        op.f("ix_compliance_checks_employee_upn"), table_name="compliance_checks"
    )
    op.drop_index(
        op.f("ix_compliance_checks_created_at"), table_name="compliance_checks"
    )
    op.drop_index(
        op.f("ix_compliance_checks_compliance_status"), table_name="compliance_checks"
    )
    op.drop_index(
        op.f("ix_compliance_checks_check_run_id"), table_name="compliance_checks"
    )
    op.drop_table("compliance_checks")

    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_last_login"), table_name="users")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")

    op.drop_index(op.f("ix_system_roles_system_name"), table_name="system_roles")
    op.drop_index(op.f("ix_system_roles_role_type"), table_name="system_roles")
    op.drop_index(op.f("ix_system_roles_role_name"), table_name="system_roles")
    op.drop_index(op.f("ix_system_roles_is_active"), table_name="system_roles")
    op.drop_index(op.f("ix_system_roles_created_at"), table_name="system_roles")
    op.drop_table("system_roles")

    op.drop_index(op.f("ix_search_cache_search_type"), table_name="search_cache")
    op.drop_index(op.f("ix_search_cache_search_query"), table_name="search_cache")
    op.drop_index(op.f("ix_search_cache_expires_at"), table_name="search_cache")
    op.drop_index(op.f("ix_search_cache_created_at"), table_name="search_cache")
    op.drop_table("search_cache")

    op.drop_index(op.f("ix_job_codes_job_code"), table_name="job_codes")
    op.drop_index(op.f("ix_job_codes_is_active"), table_name="job_codes")
    op.drop_index(op.f("ix_job_codes_department"), table_name="job_codes")
    op.drop_index(op.f("ix_job_codes_created_at"), table_name="job_codes")
    op.drop_table("job_codes")

    op.drop_index(op.f("ix_genesys_skills_service_name"), table_name="genesys_skills")
    op.drop_index(op.f("ix_genesys_skills_service_id"), table_name="genesys_skills")
    op.drop_index(op.f("ix_genesys_skills_is_active"), table_name="genesys_skills")
    op.drop_index(op.f("ix_genesys_skills_created_at"), table_name="genesys_skills")
    op.drop_table("genesys_skills")

    op.drop_index(
        op.f("ix_genesys_locations_service_name"), table_name="genesys_locations"
    )
    op.drop_index(
        op.f("ix_genesys_locations_service_id"), table_name="genesys_locations"
    )
    op.drop_index(
        op.f("ix_genesys_locations_is_active"), table_name="genesys_locations"
    )
    op.drop_index(
        op.f("ix_genesys_locations_created_at"), table_name="genesys_locations"
    )
    op.drop_table("genesys_locations")

    op.drop_index(op.f("ix_genesys_groups_service_name"), table_name="genesys_groups")
    op.drop_index(op.f("ix_genesys_groups_service_id"), table_name="genesys_groups")
    op.drop_index(op.f("ix_genesys_groups_is_active"), table_name="genesys_groups")
    op.drop_index(op.f("ix_genesys_groups_created_at"), table_name="genesys_groups")
    op.drop_table("genesys_groups")

    op.drop_index(op.f("ix_error_log_user_email"), table_name="error_log")
    op.drop_index(op.f("ix_error_log_success"), table_name="error_log")
    op.drop_index(op.f("ix_error_log_severity"), table_name="error_log")
    op.drop_index(op.f("ix_error_log_session_id"), table_name="error_log")
    op.drop_index(op.f("ix_error_log_ip_address"), table_name="error_log")
    op.drop_index(op.f("ix_error_log_error_type"), table_name="error_log")
    op.drop_index(op.f("ix_error_log_created_at"), table_name="error_log")
    op.drop_table("error_log")

    op.drop_index(
        op.f("ix_employee_role_assignments_system_name"),
        table_name="employee_role_assignments",
    )
    op.drop_index(
        op.f("ix_employee_role_assignments_role_name"),
        table_name="employee_role_assignments",
    )
    op.drop_index(
        op.f("ix_employee_role_assignments_last_verified"),
        table_name="employee_role_assignments",
    )
    op.drop_index(
        op.f("ix_employee_role_assignments_is_active"),
        table_name="employee_role_assignments",
    )
    op.drop_index(
        op.f("ix_employee_role_assignments_employee_upn"),
        table_name="employee_role_assignments",
    )
    op.drop_index(
        op.f("ix_employee_role_assignments_created_at"),
        table_name="employee_role_assignments",
    )
    op.drop_table("employee_role_assignments")

    op.drop_index("idx_employee_profiles_upn", table_name="employee_profiles")
    op.drop_index("idx_employee_profiles_live_role", table_name="employee_profiles")
    op.drop_index("idx_employee_profiles_ks_login_lock", table_name="employee_profiles")
    op.drop_index(
        "idx_employee_profiles_keystone_expected_role", table_name="employee_profiles"
    )
    op.drop_table("employee_profiles")

    op.drop_index(
        op.f("ix_compliance_check_runs_status"), table_name="compliance_check_runs"
    )
    op.drop_index(
        op.f("ix_compliance_check_runs_started_by"), table_name="compliance_check_runs"
    )
    op.drop_index(
        op.f("ix_compliance_check_runs_started_at"), table_name="compliance_check_runs"
    )
    op.drop_index(
        op.f("ix_compliance_check_runs_run_id"), table_name="compliance_check_runs"
    )
    op.drop_index(
        op.f("ix_compliance_check_runs_created_at"), table_name="compliance_check_runs"
    )
    op.drop_table("compliance_check_runs")

    op.drop_index(op.f("ix_audit_log_user_email"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_success"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_session_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_search_query"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_ip_address"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_event_type"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_created_at"), table_name="audit_log")
    op.drop_table("audit_log")

    op.drop_index(op.f("ix_api_tokens_service_name"), table_name="api_tokens")
    op.drop_index(op.f("ix_api_tokens_expires_at"), table_name="api_tokens")
    op.drop_index(op.f("ix_api_tokens_created_at"), table_name="api_tokens")
    op.drop_table("api_tokens")

    op.drop_index(op.f("ix_access_attempts_user_email"), table_name="access_attempts")
    op.drop_index(op.f("ix_access_attempts_success"), table_name="access_attempts")
    op.drop_index(op.f("ix_access_attempts_session_id"), table_name="access_attempts")
    op.drop_index(op.f("ix_access_attempts_ip_address"), table_name="access_attempts")
    op.drop_index(op.f("ix_access_attempts_created_at"), table_name="access_attempts")
    op.drop_table("access_attempts")
    # ### end Alembic commands ###
